import type { AppItem } from '../types';

export const APPS: AppItem[] = [
  {
    id: 'youtube',
    name: 'YouTube',
    icon: 'https://www.youtube.com/favicon.ico',
    color: '#FF0000',
    launchUrl: 'https://www.youtube.com',
    launchMode: 'tab',
    description: 'Videos & Live',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    icon: 'https://assets.nflxext.com/us/ffe/siteui/common/icons/nficon2016.ico',
    color: '#E50914',
    launchUrl: 'https://www.netflix.com',
    launchMode: 'tab',
    description: 'Movies & TV',
  },
  {
    id: 'prime',
    name: 'Prime Video',
    icon: 'https://m.media-amazon.com/images/G/01/digital/video/acquisition/favicon/favicon.ico',
    color: '#00A8E1',
    launchUrl: 'https://www.primevideo.com',
    launchMode: 'tab',
    description: 'Amazon Originals',
  },
  {
    id: 'disney',
    name: 'Disney+',
    icon: 'https://static-assets.bamgrid.com/product/disneyplus/static/favicon.ico',
    color: '#0063E5',
    launchUrl: 'https://www.disneyplus.com',
    launchMode: 'tab',
    description: 'Disney & Marvel',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    icon: 'https://static.twitchsvc.net/images/favicon.ico',
    color: '#9147FF',
    launchUrl: 'https://www.twitch.tv',
    launchMode: 'tab',
    description: 'Live Streaming',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    icon: 'https://open.scdn.co/cdn/images/favicon.5cb2bd30.ico',
    color: '#1DB954',
    launchUrl: 'https://open.spotify.com',
    launchMode: 'tab',
    description: 'Music & Podcasts',
  },
  {
    id: 'hulu',
    name: 'Hulu',
    icon: 'https://www.hulu.com/favicon.ico',
    color: '#1CE783',
    launchUrl: 'https://www.hulu.com',
    launchMode: 'tab',
    description: 'Shows & Movies',
  },
  {
    id: 'hbo',
    name: 'HBO Max',
    icon: 'https://www.max.com/favicon.ico',
    color: '#6B2D9A',
    launchUrl: 'https://www.max.com',
    launchMode: 'tab',
    description: 'HBO Originals',
  },
  {
    id: 'apple',
    name: 'Apple TV+',
    icon: 'https://tv.apple.com/favicon.ico',
    color: '#555555',
    launchUrl: 'https://tv.apple.com',
    launchMode: 'tab',
    description: 'Apple Originals',
  },
  {
    id: 'peacock',
    name: 'Peacock',
    icon: 'https://www.peacocktv.com/favicon.ico',
    color: '#F7C948',
    launchUrl: 'https://www.peacocktv.com',
    launchMode: 'tab',
    description: 'NBC & More',
  },
  {
    id: 'paramount',
    name: 'Paramount+',
    icon: 'https://www.paramountplus.com/favicon.ico',
    color: '#0064FF',
    launchUrl: 'https://www.paramountplus.com',
    launchMode: 'tab',
    description: 'CBS & Paramount',
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    icon: 'https://www.crunchyroll.com/favicon.ico',
    color: '#F47521',
    launchUrl: 'https://www.crunchyroll.com',
    launchMode: 'tab',
    description: 'Anime',
  },
];
