import type { AppItem } from '../types';

// White SVG icons from simpleicons CDN — reliable, no CORS issues
const SI = (slug: string) => `https://cdn.simpleicons.org/${slug}/ffffff`;

export const APPS: AppItem[] = [
  {
    id: 'youtube',
    name: 'YouTube',
    icon: SI('youtube'),
    color: '#FF0000',
    launchUrl: 'https://www.youtube.com',
    launchMode: 'tab',
    description: 'Videos & Live',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    icon: SI('netflix'),
    color: '#E50914',
    launchUrl: 'https://www.netflix.com',
    launchMode: 'tab',
    description: 'Movies & TV',
  },
  {
    id: 'prime',
    name: 'Prime Video',
    icon: SI('primevideo'),
    color: '#00A8E1',
    launchUrl: 'https://www.primevideo.com',
    launchMode: 'tab',
    description: 'Amazon Originals',
  },
  {
    id: 'disney',
    name: 'Disney+',
    icon: SI('disneyplus'),
    color: '#0063E5',
    launchUrl: 'https://www.disneyplus.com',
    launchMode: 'tab',
    description: 'Disney & Marvel',
  },
  {
    id: 'hotstar',
    name: 'Hotstar',
    icon: SI('hotstar'),
    color: '#1F80E0',
    launchUrl: 'https://www.hotstar.com',
    launchMode: 'tab',
    description: 'Sports & Shows',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    icon: SI('twitch'),
    color: '#9147FF',
    launchUrl: 'https://www.twitch.tv',
    launchMode: 'tab',
    description: 'Live Streaming',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    icon: SI('spotify'),
    color: '#1DB954',
    launchUrl: 'https://open.spotify.com',
    launchMode: 'tab',
    description: 'Music & Podcasts',
  },
  {
    id: 'hulu',
    name: 'Hulu',
    icon: SI('hulu'),
    color: '#1CE783',
    launchUrl: 'https://www.hulu.com',
    launchMode: 'tab',
    description: 'Shows & Movies',
  },
  {
    id: 'hbo',
    name: 'HBO Max',
    icon: SI('hbo'),
    color: '#6B2D9A',
    launchUrl: 'https://www.max.com',
    launchMode: 'tab',
    description: 'HBO Originals',
  },
  {
    id: 'apple',
    name: 'Apple TV+',
    icon: SI('appletv'),
    color: '#555555',
    launchUrl: 'https://tv.apple.com',
    launchMode: 'tab',
    description: 'Apple Originals',
  },
  {
    id: 'paramount',
    name: 'Paramount+',
    icon: SI('paramountplus'),
    color: '#0064FF',
    launchUrl: 'https://www.paramountplus.com',
    launchMode: 'tab',
    description: 'CBS & Paramount',
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    icon: SI('crunchyroll'),
    color: '#F47521',
    launchUrl: 'https://www.crunchyroll.com',
    launchMode: 'tab',
    description: 'Anime',
  },
];
