import type { ChannelCategory, LiveChannel } from '../types';

export const LIVE_TV_CATEGORIES: {
  id: ChannelCategory;
  label: string;
  emoji: string;
}[] = [
  { id: 'news',      label: 'English News', emoji: '🌍' },
  { id: 'hindi',     label: 'Hindi',        emoji: '🇮🇳' },
  { id: 'telugu',    label: 'Telugu',       emoji: '🎭' },
  { id: 'tamil',     label: 'Tamil',        emoji: '🌺' },
  { id: 'kannada',   label: 'Kannada',      emoji: '🏰' },
  { id: 'malayalam', label: 'Malayalam',    emoji: '🌴' },
  { id: 'marathi',   label: 'Marathi/Bengali', emoji: '🏛️' },
  { id: 'music',     label: 'Music',        emoji: '🎵' },
  { id: 'movies',    label: 'Movies',       emoji: '🎬' },
  { id: 'sports',    label: 'Sports',       emoji: '⚽' },
  { id: 'gaming',    label: 'Gaming',       emoji: '🎮' },
];

// YouTube channel IDs (UC... format) are needed for the in-app live embed.
// Verify/update at: youtube.com/@ChannelHandle → View Page Source → "channelId"

export const LIVE_TV_CHANNELS: Record<ChannelCategory, LiveChannel[]> = {

  // ──────────────────────────────────────────────────────────────────
  // INTERNATIONAL / ENGLISH NEWS
  // ──────────────────────────────────────────────────────────────────
  news: [
    {
      channelId: 'republic-world',
      ytChannelId: 'UCeInoLJPd1txowe5okm9vcg',
      channelName: 'Republic World',
      category: 'news',
      liveUrl: 'https://www.youtube.com/@RepublicWorld/live',
      color: '#E53935',
      tagline: 'India\'s No. 1 English news',
    },
    {
      channelId: 'ndtv',
      ytChannelId: 'UCNjHgFKkXKapIpgCUBnhEkQ',
      channelName: 'NDTV',
      category: 'news',
      liveUrl: 'https://www.youtube.com/@ndtv/live',
      color: '#CC0000',
      tagline: 'New Delhi Television Limited',
    },
    {
      channelId: 'wion',
      ytChannelId: 'UCrAmDDpFFHWdkVLRR4axQwQ',
      channelName: 'WION',
      category: 'news',
      liveUrl: 'https://www.youtube.com/@WIONews/live',
      color: '#E91E63',
      tagline: 'World is One News',
    },
    {
      channelId: 'bbc-news',
      ytChannelId: 'UC16niRr50-MSBwiO3YDb3RA',
      channelName: 'BBC News',
      category: 'news',
      liveUrl: 'https://www.youtube.com/@BBCNews/live',
      color: '#C0392B',
      tagline: 'The world\'s broadcaster',
    },
    {
      channelId: 'al-jazeera',
      ytChannelId: 'UCNye-wNBqNL5ZzHSJj3l8Bg',
      channelName: 'Al Jazeera English',
      category: 'news',
      liveUrl: 'https://www.youtube.com/@AlJazeeraEnglish/live',
      color: '#E65100',
      tagline: 'Global news & in-depth journalism',
    },
    {
      channelId: 'cnn',
      ytChannelId: 'UCVTyTA7KZpC4tnIXZ4OL8-Q',
      channelName: 'CNN',
      category: 'news',
      liveUrl: 'https://www.youtube.com/@CNN/live',
      color: '#CC0000',
      tagline: 'CNN — world news 24/7',
    },
    {
      channelId: 'dw-news',
      ytChannelId: 'UCknLrEdhRCp1aegoMqRaCZg',
      channelName: 'DW News',
      category: 'news',
      liveUrl: 'https://www.youtube.com/@DWNews/live',
      color: '#0D47A1',
      tagline: 'Deutsche Welle — made for minds',
    },
    {
      channelId: 'france24',
      ytChannelId: 'UCQfWjDQs7HzJFNqDH0mk-kg',
      channelName: 'France 24',
      category: 'news',
      liveUrl: 'https://www.youtube.com/@FRANCE24English/live',
      color: '#1565C0',
      tagline: 'Live from Paris',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // HINDI — News + Entertainment + Devotional
  // ──────────────────────────────────────────────────────────────────
  hindi: [
    {
      channelId: 'aaj-tak',
      ytChannelId: 'UCt4t-jeY85JegMlZ-E5UWuQ',
      channelName: 'Aaj Tak',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@aajtak/live',
      color: '#E20E21',
      tagline: 'India\'s No. 1 Hindi news channel',
      language: 'Hindi',
    },
    {
      channelId: 'abp-news',
      ytChannelId: 'UC8oXKHJ0lnDJBbJWQS2yJfQ',
      channelName: 'ABP News',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@abpnews/live',
      color: '#E53935',
      tagline: 'Sahi maayne mein',
      language: 'Hindi',
    },
    {
      channelId: 'zee-news',
      ytChannelId: 'UCIlCOHYlGKqeGqzQjzDjB9g',
      channelName: 'Zee News',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@zeenews/live',
      color: '#003399',
      tagline: 'Hindi news round the clock',
      language: 'Hindi',
    },
    {
      channelId: 'ndtv-india',
      ytChannelId: 'UCZFMm1mMw0F81Z37aaEzTUA',
      channelName: 'NDTV India',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@ndtvindia/live',
      color: '#CC0000',
      tagline: 'Hindi news broadcast',
      language: 'Hindi',
    },
    {
      channelId: 'india-tv',
      ytChannelId: 'UCoS6IjV7DQFBNwmFkGFW5Qg',
      channelName: 'India TV',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@IndiaTV/live',
      color: '#B71C1C',
      tagline: 'Aap ki awaaz',
      language: 'Hindi',
    },
    {
      channelId: 'republic-bharat',
      ytChannelId: 'UCA6MAaJGHlbDtG6bKTxfJHg',
      channelName: 'Republic Bharat',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@RepublicBharat/live',
      color: '#F44336',
      tagline: 'Voted India\'s No.1 Hindi news',
      language: 'Hindi',
    },
    {
      channelId: 'tv9-bharatvarsh',
      ytChannelId: 'UCHgzMQLMuVY-pN_2IzPCpxw',
      channelName: 'TV9 Bharatvarsh',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@TV9Bharatvarsh/live',
      color: '#D32F2F',
      tagline: 'TV9 Network Hindi',
      language: 'Hindi',
    },
    {
      channelId: 'news18-india',
      ytChannelId: 'UCbhf_ycEBqB8BxC3pJpDL8w',
      channelName: 'News18 India',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@News18India/live',
      color: '#C62828',
      tagline: 'Network 18 Hindi news',
      language: 'Hindi',
    },
    {
      channelId: 'set-india',
      ytChannelId: 'UCpEhnqL0y41EpW2TvWAHD7Q',
      channelName: 'SET India (Sony)',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@setindia/live',
      color: '#0D47A1',
      tagline: 'Sony Entertainment Television',
      language: 'Hindi',
    },
    {
      channelId: 'zee-tv',
      ytChannelId: 'UCppHoOe9oHMBfEFHSEbkB1g',
      channelName: 'Zee TV',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@ZeeTV/live',
      color: '#4527A0',
      tagline: 'Zee Entertainment Hindi',
      language: 'Hindi',
    },
    {
      channelId: 'colors-tv',
      ytChannelId: 'UC6YGhbLQYl5I6hBJmGSTRQA',
      channelName: 'Colors TV',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@ColorsTV/live',
      color: '#FF6B00',
      tagline: 'Kuch toh hua hai…',
      language: 'Hindi',
    },
    {
      channelId: 'star-plus',
      ytChannelId: 'UChLRzlxKxe1JJwmAHfYUL7A',
      channelName: 'Star Plus',
      category: 'hindi',
      liveUrl: 'https://www.youtube.com/@StarPlus/live',
      color: '#F7C74E',
      tagline: 'Rishta wahi soch nayi',
      language: 'Hindi',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // TELUGU — News + Entertainment + Music
  // ──────────────────────────────────────────────────────────────────
  telugu: [
    {
      channelId: 'tv9-telugu',
      ytChannelId: 'UCnzXMjJIgwLUaFKGLMXVGCw',
      channelName: 'TV9 Telugu',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@TV9Telugu/live',
      color: '#C40000',
      tagline: 'Telugu news 24x7',
      language: 'Telugu',
    },
    {
      channelId: 'abn-andhra',
      ytChannelId: 'UC8o0BgzFQM3jQx5LHAY2eTg',
      channelName: 'ABN Andhra Jyothi',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@ABNAndraJyothi/live',
      color: '#D32F2F',
      tagline: 'Andhra Jyothi — voice of Telugu',
      language: 'Telugu',
    },
    {
      channelId: 'ntv-telugu',
      ytChannelId: 'UCQGqX5Ndpm4SNE0e1E3jtHg',
      channelName: 'NTV Telugu',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@NTVTelugu/live',
      color: '#1565C0',
      tagline: 'NTV Telugu news',
      language: 'Telugu',
    },
    {
      channelId: 'sakshi-tv',
      ytChannelId: 'UCN1hnUccO4FD5WfM7ixftzw',
      channelName: 'Sakshi TV',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@SakshiTV/live',
      color: '#E53935',
      tagline: 'Sakshi — witness the truth',
      language: 'Telugu',
    },
    {
      channelId: 'tv5-telugu',
      ytChannelId: 'UCsyRnGQtgRc_cGdV4rEBxEA',
      channelName: 'TV5 News Telugu',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@TV5News/live',
      color: '#2E7D32',
      tagline: 'Yedi nesam yedi vishayam',
      language: 'Telugu',
    },
    {
      channelId: 'etv-telugu',
      ytChannelId: 'UCN0EJGKN59M3WRRKrJNWOGw',
      channelName: 'ETV Telugu',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@ETVTeluguNews/live',
      color: '#6A1B9A',
      tagline: 'ETV Telugu entertainment & news',
      language: 'Telugu',
    },
    {
      channelId: 'gemini-tv',
      ytChannelId: 'UCbmNph6atAoGfqLoCL_duAg',
      channelName: 'Gemini TV',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@GeminiTV/live',
      color: '#E91E63',
      tagline: 'Star India Telugu channel',
      language: 'Telugu',
    },
    {
      channelId: 'aditya-music',
      ytChannelId: 'UCQnVfLaRqhN9TE9OL7AMELg',
      channelName: 'Aditya Music',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@AdityaMusic/live',
      color: '#FF6F00',
      tagline: 'Telugu music non-stop',
      language: 'Telugu',
    },
    {
      channelId: 'lahari-music',
      ytChannelId: 'UC-iN7N3gnqKlGHgqn-M-bpw',
      channelName: 'Lahari Music',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@LahariMusic/live',
      color: '#00897B',
      tagline: 'Telugu & Kannada hits',
      language: 'Telugu',
    },
    {
      channelId: 'suman-tv',
      ytChannelId: 'UC0EhFNPoNklsbQFdKlO6P3g',
      channelName: 'Suman TV',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@SumanTV/live',
      color: '#F57C00',
      tagline: 'Telugu entertainment',
      language: 'Telugu',
    },
    {
      channelId: 'mahaa-news',
      ytChannelId: 'UCrDY5I0hKFd0FaGSs3U8jDw',
      channelName: 'Mahaa News',
      category: 'telugu',
      liveUrl: 'https://www.youtube.com/@MahaaNews/live',
      color: '#AD1457',
      tagline: 'Telugu live news',
      language: 'Telugu',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // TAMIL — News + Entertainment + Music
  // ──────────────────────────────────────────────────────────────────
  tamil: [
    {
      channelId: 'sun-news',
      ytChannelId: 'UCzME0HRBcMhqCYlRDBoV_bg',
      channelName: 'Sun News',
      category: 'tamil',
      liveUrl: 'https://www.youtube.com/@SunNews/live',
      color: '#FF6F00',
      tagline: 'Tamil live news',
      language: 'Tamil',
    },
    {
      channelId: 'puthiya-thalaimurai',
      ytChannelId: 'UC3uyIo2WpvGKhAoQnN-Rceg',
      channelName: 'Puthiya Thalaimurai',
      category: 'tamil',
      liveUrl: 'https://www.youtube.com/@PuthiyaThalaimurai/live',
      color: '#D81B60',
      tagline: 'Breaking news in Tamil',
      language: 'Tamil',
    },
    {
      channelId: 'polimer-news',
      ytChannelId: 'UCjJnxwA_36iqHCl3oJRQfKA',
      channelName: 'Polimer News',
      category: 'tamil',
      liveUrl: 'https://www.youtube.com/@PolimerNews/live',
      color: '#F4511E',
      tagline: 'News & current affairs',
      language: 'Tamil',
    },
    {
      channelId: 'news18-tamilnadu',
      ytChannelId: 'UCRiNNBerXG4GUxdQR1a53FA',
      channelName: 'News18 Tamil Nadu',
      category: 'tamil',
      liveUrl: 'https://www.youtube.com/@News18TamilNadu/live',
      color: '#C62828',
      tagline: 'Tamil news Network18',
      language: 'Tamil',
    },
    {
      channelId: 'vijay-tv',
      ytChannelId: 'UCUCRMU6uQUVHlvR0MBqjxig',
      channelName: 'Vijay TV',
      category: 'tamil',
      liveUrl: 'https://www.youtube.com/@vijaytelevision/live',
      color: '#1565C0',
      tagline: 'Star Vijay entertainment',
      language: 'Tamil',
    },
    {
      channelId: 'kalaignar-tv',
      ytChannelId: 'UCBHuJLQQC42Q2mPc4Q9kS_g',
      channelName: 'Kalaignar TV',
      category: 'tamil',
      liveUrl: 'https://www.youtube.com/@KalaignarTV/live',
      color: '#283593',
      tagline: 'Kalaignar — Tamil entertainment',
      language: 'Tamil',
    },
    {
      channelId: 'sun-tv',
      ytChannelId: 'UCQyWmIlL2LiHWZ5n4yRSI7A',
      channelName: 'Sun TV',
      category: 'tamil',
      liveUrl: 'https://www.youtube.com/@suntv/live',
      color: '#E65100',
      tagline: 'Tamil GEC No. 1',
      language: 'Tamil',
    },
    {
      channelId: 'makkal-tv',
      ytChannelId: 'UC3yFcHNrIDHXdpYEON4XUUQ',
      channelName: 'Makkal TV',
      category: 'tamil',
      liveUrl: 'https://www.youtube.com/@MakkalTVLive/live',
      color: '#2E7D32',
      tagline: 'Makkal kural',
      language: 'Tamil',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // KANNADA
  // ──────────────────────────────────────────────────────────────────
  kannada: [
    {
      channelId: 'tv9-kannada',
      ytChannelId: 'UCXq9uMm8ej3Xp38lxrGMFaA',
      channelName: 'TV9 Kannada',
      category: 'kannada',
      liveUrl: 'https://www.youtube.com/@TV9Kannada/live',
      color: '#C62828',
      tagline: 'Kannada live news',
      language: 'Kannada',
    },
    {
      channelId: 'suvarna-news',
      ytChannelId: 'UCjG5cEMbw8r1P0KBcKFW6Og',
      channelName: 'Suvarna News',
      category: 'kannada',
      liveUrl: 'https://www.youtube.com/@SuvarnaNewsKannada/live',
      color: '#E65100',
      tagline: 'Suvarna — Kannada news',
      language: 'Kannada',
    },
    {
      channelId: 'star-suvarna',
      ytChannelId: 'UCzRuCOGiBG9tMqZ4L7XggxA',
      channelName: 'Star Suvarna',
      category: 'kannada',
      liveUrl: 'https://www.youtube.com/@StarSuvarna/live',
      color: '#F9A825',
      tagline: 'Star Suvarna entertainment',
      language: 'Kannada',
    },
    {
      channelId: 'zee-kannada',
      ytChannelId: 'UCQp5pKhD6FRwJt4f0IiHLqQ',
      channelName: 'Zee Kannada',
      category: 'kannada',
      liveUrl: 'https://www.youtube.com/@ZeeKannada/live',
      color: '#4527A0',
      tagline: 'Zee Kannada GEC',
      language: 'Kannada',
    },
    {
      channelId: 'colors-super',
      ytChannelId: 'UCU7pDMfVQjJLNdQmE6xv7mA',
      channelName: 'Colors Super Kannada',
      category: 'kannada',
      liveUrl: 'https://www.youtube.com/@ColorsSuper/live',
      color: '#FF6B00',
      tagline: 'Colors Super Kannada',
      language: 'Kannada',
    },
    {
      channelId: 'public-tv-kannada',
      ytChannelId: 'UCQPpAGvubPkBmvAhg0-VQxg',
      channelName: 'Public TV Kannada',
      category: 'kannada',
      liveUrl: 'https://www.youtube.com/@PublicTVKannada/live',
      color: '#1976D2',
      tagline: 'Public TV — Kannada news',
      language: 'Kannada',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // MALAYALAM
  // ──────────────────────────────────────────────────────────────────
  malayalam: [
    {
      channelId: 'asianet-news',
      ytChannelId: 'UCjOBfC4GGmjVhTVSLBCqS1A',
      channelName: 'Asianet News',
      category: 'malayalam',
      liveUrl: 'https://www.youtube.com/@AsianetNews/live',
      color: '#AD1457',
      tagline: 'Kerala\'s No.1 news channel',
      language: 'Malayalam',
    },
    {
      channelId: 'manorama-news',
      ytChannelId: 'UCt_rqNFfQmxWoTMFjjTzEaw',
      channelName: 'Manorama News',
      category: 'malayalam',
      liveUrl: 'https://www.youtube.com/@ManoramaNews/live',
      color: '#B71C1C',
      tagline: 'Manorama News — Kerala\'s trusted',
      language: 'Malayalam',
    },
    {
      channelId: 'janam-tv',
      ytChannelId: 'UC-XvBn2OBCbgC6XAM_RJi7A',
      channelName: 'Janam TV',
      category: 'malayalam',
      liveUrl: 'https://www.youtube.com/@JanamTV/live',
      color: '#283593',
      tagline: 'Janam TV Malayalam',
      language: 'Malayalam',
    },
    {
      channelId: 'reporter-live',
      ytChannelId: 'UCBK2LRfDLXLGxLKd3cB-aEA',
      channelName: 'Reporter Live',
      category: 'malayalam',
      liveUrl: 'https://www.youtube.com/@ReporterLive/live',
      color: '#006064',
      tagline: 'Reporter Malayalam news',
      language: 'Malayalam',
    },
    {
      channelId: 'mazhavil-manorama',
      ytChannelId: 'UCEYCjBKq2bswB9sLJVAH64g',
      channelName: 'Mazhavil Manorama',
      category: 'malayalam',
      liveUrl: 'https://www.youtube.com/@MazhavilManorama/live',
      color: '#7B1FA2',
      tagline: 'Mazhavil — Malayalam entertainment',
      language: 'Malayalam',
    },
    {
      channelId: 'asianet',
      ytChannelId: 'UCzGqGn4STn1VIgdMHQ1cxCg',
      channelName: 'Asianet',
      category: 'malayalam',
      liveUrl: 'https://www.youtube.com/@asianet/live',
      color: '#E91E63',
      tagline: 'Asianet Malayalam GEC',
      language: 'Malayalam',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // MARATHI + BENGALI + PUNJABI + GUJARATI
  // ──────────────────────────────────────────────────────────────────
  marathi: [
    {
      channelId: 'abp-majha',
      ytChannelId: 'UC5yiG6BBB0FP_HLnFRSjYVA',
      channelName: 'ABP Majha',
      category: 'marathi',
      liveUrl: 'https://www.youtube.com/@ABPMajha/live',
      color: '#E53935',
      tagline: 'Maharashtra\'s #1 Marathi news',
      language: 'Marathi',
    },
    {
      channelId: 'tv9-marathi',
      ytChannelId: 'UCz8e_7_DsexZBHMBELkFqGA',
      channelName: 'TV9 Marathi',
      category: 'marathi',
      liveUrl: 'https://www.youtube.com/@TV9Marathi/live',
      color: '#C62828',
      tagline: 'TV9 Marathi news',
      language: 'Marathi',
    },
    {
      channelId: 'zee-24-taas',
      ytChannelId: 'UC1jmOoSEZk7y0DOEn5TbOTQ',
      channelName: 'Zee 24 Taas',
      category: 'marathi',
      liveUrl: 'https://www.youtube.com/@Zee24Taas/live',
      color: '#1565C0',
      tagline: 'Zee Marathi news 24 hours',
      language: 'Marathi',
    },
    {
      channelId: 'abp-ananda',
      ytChannelId: 'UCdePdXqvz43tO7gZZsqBc4g',
      channelName: 'ABP Ananda',
      category: 'marathi',
      liveUrl: 'https://www.youtube.com/@ABPAnanda/live',
      color: '#AD1457',
      tagline: 'ABP Bengali news',
      language: 'Bengali',
    },
    {
      channelId: 'zee-24-ghanta',
      ytChannelId: 'UCFOcC60r-qc4vvFBPmXYK7g',
      channelName: 'Zee 24 Ghanta',
      category: 'marathi',
      liveUrl: 'https://www.youtube.com/@Zee24Ghanta/live',
      color: '#6A1B9A',
      tagline: 'Zee Bengali news 24 hours',
      language: 'Bengali',
    },
    {
      channelId: 'ptc-news',
      ytChannelId: 'UCqvZQbxRyWBwrFnuEJQ3HWQ',
      channelName: 'PTC News Punjabi',
      category: 'marathi',
      liveUrl: 'https://www.youtube.com/@PTCNewsOfficial/live',
      color: '#F57C00',
      tagline: 'Punjabi news & entertainment',
      language: 'Punjabi',
    },
    {
      channelId: 'abtak-gujarati',
      ytChannelId: 'UCYIKFnRcBa4j1oS7mX8B9OQ',
      channelName: 'ABtak Gujarati',
      category: 'marathi',
      liveUrl: 'https://www.youtube.com/@ABtakTV/live',
      color: '#00695C',
      tagline: 'Gujarati news live',
      language: 'Gujarati',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // MUSIC — Indian music channels
  // ──────────────────────────────────────────────────────────────────
  music: [
    {
      channelId: 't-series',
      ytChannelId: 'UCq-Fj5jknLsUf-MWSy4_brA',
      channelName: 'T-Series',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@tseries/live',
      color: '#FF0000',
      tagline: 'India\'s #1 music label',
    },
    {
      channelId: 'zee-music',
      ytChannelId: 'UCFFbwnve3yF62-tVXkTyHqg',
      channelName: 'Zee Music Company',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@ZeeMusicCompany/live',
      color: '#9B2990',
      tagline: 'Latest Bollywood hits',
    },
    {
      channelId: 'saregama',
      ytChannelId: 'UC9EKqIHG5GCYP1JF-WOzBuQ',
      channelName: 'Saregama India',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@SaregamaIndia/live',
      color: '#C62828',
      tagline: 'India\'s heritage music label',
    },
    {
      channelId: 'tips-music',
      ytChannelId: 'UCmBdhGmKDGMhzLQ2YDKR3LA',
      channelName: 'Tips Music',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@TipsMusic/live',
      color: '#E53935',
      tagline: 'Tips music — Bollywood hits',
    },
    {
      channelId: 'sony-music-india',
      ytChannelId: 'UCRK32MiHABnYYBWn0BJZDYA',
      channelName: 'Sony Music India',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@SonyMusicIndia/live',
      color: '#1565C0',
      tagline: 'Sony India hits',
    },
    {
      channelId: 'aditya-music-main',
      ytChannelId: 'UCQnVfLaRqhN9TE9OL7AMELg',
      channelName: 'Aditya Music',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@AdityaMusic/live',
      color: '#E65100',
      tagline: 'Telugu & South music hits',
    },
    {
      channelId: 'lahari-music-main',
      ytChannelId: 'UC-iN7N3gnqKlGHgqn-M-bpw',
      channelName: 'Lahari Music',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@LahariMusic/live',
      color: '#00897B',
      tagline: 'Telugu & Kannada classics',
    },
    {
      channelId: 'lofi-girl',
      ytChannelId: 'UCSJ4gkVC6NrvII8umztf0Ow',
      channelName: 'Lofi Girl',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@LofiGirl/live',
      color: '#5C6BC0',
      tagline: '24/7 lofi hip hop radio',
    },
    {
      channelId: 'ncs',
      ytChannelId: 'UC_aEa8K-EOJ3D6gOs7HcyNg',
      channelName: 'NoCopyrightSounds',
      category: 'music',
      liveUrl: 'https://www.youtube.com/@NoCopyrightSounds/live',
      color: '#212121',
      tagline: 'Free music for creators',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // MOVIES — Hindi & South Indian movies
  // ──────────────────────────────────────────────────────────────────
  movies: [
    {
      channelId: 'shemaroo-movies',
      ytChannelId: 'UCaFHMs7T5mfCPvKjOBmQDkQ',
      channelName: 'Shemaroo Movies',
      category: 'movies',
      liveUrl: 'https://www.youtube.com/@ShemarooMovies/live',
      color: '#E53935',
      tagline: 'Bollywood movies free',
    },
    {
      channelId: 'rajshri-movies',
      ytChannelId: 'UCVpM_A4DtIHWx1lsBNvP_kQ',
      channelName: 'Rajshri Movies',
      category: 'movies',
      liveUrl: 'https://www.youtube.com/@RajshriMovies/live',
      color: '#F57F17',
      tagline: 'Classic Bollywood films',
    },
    {
      channelId: 'goldmines',
      ytChannelId: 'UCyOqDkxH2UM0OEJhkRqXfNA',
      channelName: 'Goldmines Telefilms',
      category: 'movies',
      liveUrl: 'https://www.youtube.com/@Goldminestelefilms/live',
      color: '#F9A825',
      tagline: 'South dubbed Hindi films',
    },
    {
      channelId: 'ultra-movies',
      ytChannelId: 'UCoLFTVPLHXwfUDRIbI5eOSg',
      channelName: 'Ultra Movies',
      category: 'movies',
      liveUrl: 'https://www.youtube.com/@ultramovies/live',
      color: '#1A237E',
      tagline: 'Ultra Movies Hindi',
    },
    {
      channelId: 'b4u-movies',
      ytChannelId: 'UCfRl5fcF0pJQJdGVGZJNSuQ',
      channelName: 'B4U Movies',
      category: 'movies',
      liveUrl: 'https://www.youtube.com/@B4UMovies/live',
      color: '#880E4F',
      tagline: 'Bollywood 24/7 live',
    },
    {
      channelId: 'shemaroo-filmigraaph',
      ytChannelId: 'UCPyJmTpFBi6MkA3EefknzPw',
      channelName: 'Shemaroo Filmigraaph',
      category: 'movies',
      liveUrl: 'https://www.youtube.com/@ShemarooFilmiGaane/live',
      color: '#BF360C',
      tagline: 'Hindi film songs & clips',
    },
    {
      channelId: 'sri-balaji-video',
      ytChannelId: 'UC4avMmz9aSEaYpKR7s9RqEg',
      channelName: 'Sri Balaji Video',
      category: 'movies',
      liveUrl: 'https://www.youtube.com/@SriBalajivideo/live',
      color: '#E65100',
      tagline: 'Tamil & Telugu movies',
    },
    {
      channelId: 'eagle-media-works',
      ytChannelId: 'UC5rZlbLSPyGI0VXjZ7C_m_g',
      channelName: 'Eagle Media Works',
      category: 'movies',
      liveUrl: 'https://www.youtube.com/@EagleMediaWorks/live',
      color: '#558B2F',
      tagline: 'Telugu movies & songs',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // SPORTS
  // ──────────────────────────────────────────────────────────────────
  sports: [
    {
      channelId: 'espn',
      ytChannelId: 'UCiWLfSweyRNmLpgEHekhoAg',
      channelName: 'ESPN',
      category: 'sports',
      liveUrl: 'https://www.youtube.com/@ESPN/live',
      color: '#CC0000',
      tagline: 'The worldwide leader in sports',
    },
    {
      channelId: 'sky-sports',
      ytChannelId: 'UCnu-FJMl2Wv0j_4d-4jF9pg',
      channelName: 'Sky Sports',
      category: 'sports',
      liveUrl: 'https://www.youtube.com/@SkySports/live',
      color: '#1565C0',
      tagline: 'Premier League & more',
    },
    {
      channelId: 'nba',
      ytChannelId: 'UCHD4Qjm8RAUaYbKHqRTYXGg',
      channelName: 'NBA',
      category: 'sports',
      liveUrl: 'https://www.youtube.com/@NBA/live',
      color: '#C41230',
      tagline: 'Official NBA live streams',
    },
    {
      channelId: 'icc-cricket',
      ytChannelId: 'UCiWLfSweyRNmLpgEHekhoAg',
      channelName: 'ICC Cricket',
      category: 'sports',
      liveUrl: 'https://www.youtube.com/@ICC/live',
      color: '#1B5E20',
      tagline: 'International Cricket Council',
    },
    {
      channelId: 'star-sports',
      ytChannelId: 'UCaVFpSFxHAAG8BOr5PMbLmg',
      channelName: 'Star Sports',
      category: 'sports',
      liveUrl: 'https://www.youtube.com/@StarSportsIndia/live',
      color: '#0D47A1',
      tagline: 'India\'s premium sports channel',
    },
    {
      channelId: 'eurosport',
      ytChannelId: 'UCS-f0W4bB-oEJRmL1e4r-lA',
      channelName: 'Eurosport',
      category: 'sports',
      liveUrl: 'https://www.youtube.com/@Eurosport/live',
      color: '#1976D2',
      tagline: 'European sports live',
    },
  ],

  // ──────────────────────────────────────────────────────────────────
  // GAMING
  // ──────────────────────────────────────────────────────────────────
  gaming: [
    {
      channelId: 'ign',
      ytChannelId: 'UCKy1dAqELo0zrOtPkf0eTMw',
      channelName: 'IGN',
      category: 'gaming',
      liveUrl: 'https://www.youtube.com/@IGN/live',
      color: '#CC0000',
      tagline: 'Gaming & entertainment news',
    },
    {
      channelId: 'playstation',
      ytChannelId: 'UCmhJo0-KRqbZOKUiByZBENg',
      channelName: 'PlayStation',
      category: 'gaming',
      liveUrl: 'https://www.youtube.com/@PlayStation/live',
      color: '#003087',
      tagline: 'Official PlayStation channel',
    },
    {
      channelId: 'xbox',
      ytChannelId: 'UCMAUMSO2d4Y1jJe5yjBGWYA',
      channelName: 'Xbox',
      category: 'gaming',
      liveUrl: 'https://www.youtube.com/@Xbox/live',
      color: '#107C10',
      tagline: 'Official Xbox channel',
    },
    {
      channelId: 'nintendo',
      ytChannelId: 'UCGIY_O-8vW4rfX98KlMkvRg',
      channelName: 'Nintendo',
      category: 'gaming',
      liveUrl: 'https://www.youtube.com/@Nintendo/live',
      color: '#E60012',
      tagline: 'Official Nintendo channel',
    },
    {
      channelId: 'gamespot',
      ytChannelId: 'UCzEid-lFN0VcAzpJEgpJhSQ',
      channelName: 'GameSpot',
      category: 'gaming',
      liveUrl: 'https://www.youtube.com/@GameSpot/live',
      color: '#FF6F00',
      tagline: 'Your source for gaming news',
    },
    {
      channelId: 'markiplier',
      ytChannelId: 'UCTkXRDQl0luXxVQrRQvWS6w',
      channelName: 'Markiplier',
      category: 'gaming',
      liveUrl: 'https://www.youtube.com/@markiplier/live',
      color: '#C62828',
      tagline: 'Live gaming streams',
    },
  ],
};
